export const API_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1";

export const QUERY_KEYS = {
  ADMISSION_CLASSES: ["admission-classes"],
  CURRENT_USER: ["currentUser"],
  SCHOOL_APPLICATION: ["schoolApplication"],
  SCHOOL_APPLICATIONS: ["schoolApplications"],
  TEACHER_APPLICATION: ["teacherApplication"],
  TEACHER_APPLICATIONS: ["teacherApplications"],
  USER_APPLICATION_STATUS: ["user-application-status"],
  SCHOOL_CREATE: ["created-school-application"],
  ACADEMIC_YEARS: ["academicYears"],
  ACADEMIC_YEAR: ["academicYear"],
  STUDENTS: ["students"],
  STUDENT: ["student"],
  TEACHERS: ["teachers"],
  TEACHER: ["teacher"],
  CLASSES: ["classes"],
  CLASS: ["class"],
  SUBJECTS: ["subjects"],
  SUBJECT: ["subject"],
  FEES: ["fees"],
  FEE: ["fee"],
  ATTENDANCE: ["attendance"],
  GRADES: ["grades"],
  GRADE: ["grade"],
  NOTIFICATIONS: ["notifications"],
  DASHBOARD: ["dashboard"],
};
